# Generated by Django 5.2.5 on 2025-11-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerFree', '0003_notification_userprofile_ngofoodrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
