"""
Django settings for FoodSaver project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os
from decouple import config, Csv

# ---------------------------------------------------------------
# BASE DIRECTORY CONFIGURATION
# ---------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Path to .env file (should be at same level as manage.py)
ENV_FILE = BASE_DIR / '.env'

# ---------------------------------------------------------------
# SECURITY SETTINGS
# ---------------------------------------------------------------

SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-(r(jz3e@-!nt7lp&)+^ufjqhec!#g*$k=*h&*qyp)fd)xlk-tm'
)

DEBUG = config('DEBUG', default=True, cast=bool)

# Add your domain(s) or IP(s) here when deploying
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='.pythonanywhere.com,127.0.0.1,localhost',
    cast=Csv()
)

# ---------------------------------------------------------------
# API KEYS
# ---------------------------------------------------------------
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
IPSTACK_API_KEY = config('IPSTACK_API_KEY', default='')

if not GEMINI_API_KEY:
    print("⚠️  WARNING: GEMINI_API_KEY not found in environment variables")
if not IPSTACK_API_KEY:
    print("⚠️  WARNING: IPSTACK_API_KEY not found in environment variables")

# ---------------------------------------------------------------
# DJANGO APPLICATIONS
# ---------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "HungerFree",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom Middleware
    "HungerFree.middleware.RoleBasedRedirectMiddleware",
]

ROOT_URLCONF = "FoodSaver.urls"

# ---------------------------------------------------------------
# TEMPLATES CONFIGURATION
# ---------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),  # Optional for global templates
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "FoodSaver.wsgi.application"

# ---------------------------------------------------------------
# DATABASE CONFIGURATION
# ---------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# For PythonAnywhere / production, switch to MySQL or PostgreSQL
# Example:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': config('DB_NAME', default=''),
#         'USER': config('DB_USER', default=''),
#         'PASSWORD': config('DB_PASSWORD', default=''),
#         'HOST': config('DB_HOST', default=''),
#         'PORT': config('DB_PORT', default='3306'),
#     }
# }

# ---------------------------------------------------------------
# PASSWORD VALIDATORS
# ---------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------
# STATIC FILES CONFIGURATION
# ---------------------------------------------------------------
# URL to access static files
STATIC_URL = '/static/'

# Directory where collectstatic will store files (for deployment)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directories containing your app static files (for development)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'HungerFree', 'static'),
]

# ---------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD
# ---------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------
# MEDIA FILES (OPTIONAL)
# ---------------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ---------------------------------------------------------------
# LOGGING (optional, good for debugging on PythonAnywhere)
# ---------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
